### ISSUE TITLE
github marketplace action?

### ISSUE THREAD

**Issue by naseemkullah** [DavidAnson/markdownlint-cli2#16]
Is there any plan to add a markdownlint-cli2 action to gh marketplace?

**Comment by DavidAnson** [comment]
I'll look into it.

**Comment by DavidAnson** [comment]
I may have something basic to share in a couple of days.

**Comment by jpreese** [comment]
I would second this! An image pushed to DockerHub would also be amazing for local workflows. We use:

```console
@$(DOCKER) run -v $(CURDIR):/repo -w /repo thegeeklab/markdownlint-cli docs
```

For `markdownlint`, but would like to migrate to v2.

**Comment by DavidAnson** [comment]
@jpreese Please open a separate issue for Docker. I have no Docker experience, so if you want to PR something (maybe based on CLI1's existing support for this), that would be helpful!

**Comment by DavidAnson** [comment]
@naseemkullah I haven’t had power all day, so I did about half of this on an iPad pushing somewhat blindly, but I think it should work. Give it a try?

https://github.com/marketplace/actions/markdownlint-cli2-action

**Comment by naseemkullah** [comment]
I plan to give it a go over the weekend! Thanks!!

**Comment by naseemkullah** [comment]
Seems to be working !


nit I would make the example in the marketplace doc more complete:


```
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint markdown files
        uses: DavidAnson/markdownlint-cli2-action@v1
        with:
          globs: "README.md"
 ```
