### ISSUE TITLE
Output format of pre-commit hooks very hard to read & hook documentation

### ISSUE THREAD

**Issue by skwde** [DavidAnson/markdownlint-cli2#216]
I have the following part in my `.pre-commit-config.yaml`

```yaml
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.10.0
    hooks:
      - id: markdownlint-cli2
      - id: markdownlint-cli2-fix
```

when I then run

```sh
pre-commit run --all
```

the output format is very hard to read.

It basically has  repeated blocks built like

```out
markdownlint-cli2 v0.10.0 (markdownlint v0.31.1)
Finding: <a list of files>
Linting: 28 file(s)
Summary: 2 error(s)
```

under the hook outputs for `markdownlint-cli2` and `markdownlint-cli2-fix`.

Is it possible to configure how the output looks like?
If so, is it documented? Where?
If not, can it be adjusted to have an easier to read output?

In addition, is there documentation for the different pre-commit hooks in <https://github.com/DavidAnson/markdownlint-cli2/blob/main/.pre-commit-hooks.yaml> ?

**Comment by DavidAnson** [comment]
You can change the format of output with an output formatter: https://github.com/DavidAnson/markdownlint-cli2/blob/main/doc/OutputFormatters.md

You may also want to set the `noProgress` configuration option (see README).

The pre-commit hooks each have a description field with a summary. They are basically variations on the normal, "config", "fix", and Docker command-lines. Specifics are covered in the first half of the README.

https://github.com/DavidAnson/markdownlint-cli2/blob/main/README.md

**Comment by skwde** [comment]
Ok, thanks.

I now use `markdownlint-cli2-formatter-pretty` which colors the warnings pretty nicely but I still get several blocks

```
<colored errors if there are any>
Finding: <some files, probably the onces checked>
Linting: 2 file(s)
Summary: 0 error(s)
```

I use following  `.markdownlint-cli2.yaml`

```yaml
noProgress: false

outputFormatters:
  -
    - markdownlint-cli2-formatter-pretty
    - appendLink: true
```

Besides, I cannot find any mentioning of `markdownlint-cli2-docker` or `markdownlint-cli2-config` or others, aside from deprecation warnings.
