### ISSUE TITLE
Rule like MD007 for Ordered list indentation an option?

### ISSUE THREAD

**Issue by netopsengineer** [DavidAnson/markdownlint-cli2#255]
Hello,

Firstly, thank you for your great set of tools around the Markdown ecosystem!

As with all things Markdown, the rendering tools flavor choices tend to vary, in my case, using `MkDocs` to render Markdown into a static site, I noticed that ordered lists, while not something I use frequently, my team does, and without 4 spaces on nested items, it seems to render everything in single line notation, and not nested.  It seems like the linting rules are ok with any indentation on ordered lists, so long as it is the same level of indentation, `MD005`.

So to enforce the behavior I need for both Ordered and Unordered lists with the VS Code extension, and lint in the pipeline with your other amazing tools, I'm hoping to be able to add something like my existing configuration item for `MD007`.  This is super handy, because the extension is also able to fix these in one swoop too.

```yaml
---
config:
  # MD007/ul-indent - Unordered list indentation
  MD007:
    # Spaces for indent
    indent: 4
    # Whether to indent the first level of the list
    start_indented: false
    # Spaces for first level indent (when start_indented is set)
    start_indent: 2
```
