### ISSUE TITLE
(feat) Config 'overrides' option and usage example

### ISSUE THREAD

**Issue by sfuerte** [DavidAnson/markdownlint-cli2#565]
Not an issue but rather a small feature request.

Case scenario:
- have numerous properly and fairly strictly formatted MD files in a repo;
- the same repo has `**/terraform-docs/*.md`, which far from the above.

The current `.markdownlint.yaml` as follows:
```yaml
---
default: true
MD007:
  indent: 4
MD013:
  line_length: 300
```

The only references for override options I found are:
- https://github.com/igorshubovych/markdownlint-cli/issues/53
- https://github.com/DavidAnson/markdownlint/issues/186

Which refer further to the `markdownlint` lib docs. It does mention there that it's _possible_ to configure the exclusion based on a glob. But not very clear, though.

Is it possible to do an example of the tool config that would do the described behaviour?  
Something like the following didn't work :) 
```yaml
overrides:
  - files:
      - "**/terraform-docs/*.md"
    rules:
      line_length: false
      no-inline-html: false
      no-trailing-punctuation: false
      no-duplicate-heading: false
      no-bare-urls: false
      ol-prefix: false
```
